### ISSUE TITLE
Kernel crashing upon running TubeTK functions

### ISSUE THREAD

**Issue by OminiRathore** [InsightSoftwareConsortium/ITKTubeTK#157]
Hello, 

When running the example notebook Demo-ConvertTubesToImage.ipynb, the kernel crashes upon encountering the line TubesToImageFilterType = ttk.ConvertTubesToImage[TemplateImageType]. The kernel crashes whenever I try to call a function from TubeTK. I have installed tubetk via python, I encounter this issue when running on windows and linux but not on Mac. I also tried to compile the package from scratch but the tubetk package does not get automatically build along with ITK.

**Comment by aylward** [comment]
Sounds like a wheel issue as well as broken compatibility with ITK 5.4.

I'll look into it, but it will be a week or so.

**Comment by aylward** [comment]
Thanks for your patience.

For Windows running Python 3.11, there are good wheels for itk, itk-minimalpathextraction, and itk-tubetk on pypitest (note these are on the pypitest server - not the main pypi server).   The reason these are on the test server is that there is a multi-month lag between ITK releases, and I had to make changes to ITK and TubeTK to get everything working.   The changes to ITK won't be in the 5.4 release, so we'll need to wait for the ITK 6.0 release which is probably several months away.   So, I've had to create my own (unofficial) ITK wheels.

If you are on Windows and running Python 3.11, you can download them in a NEW venv, using

    python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ itk itk-minimalpathextraction itk-tubetk

This should install the following packages (pip list | grep itk):

```
itk                       5.4.0.20240629
itk-core                  5.4.0.20240629
itk-filtering             5.4.0.20240629
itk-io                    5.4.0.20240629
itk-minimalpathextraction 2.0.0.20240629
itk-numerics              5.4.0.20240629
itk-registration          5.4.0.20240629
itk-segmentation          5.4.0.20240629
itk-tubetk                1.4.0.20240629
```

There are also wheels for ITK 5.4 on the main pyi server, BUT they will cause errors when calling certain I/O and spatial object operations (e.g., reading and writing vessel/tube ".tre" files from TubeTK) because ITK 5.4's API is missing functions now used by TubeTK.  

I will also create Ubuntu 22.04 wheels.

If you need other wheels, I can perhaps provide them - but I cannot provide Mac wheels.

I've tested using several examples, and all seems to work - and any feedback on your experience with them is welcomed!

Best regards,
Stephen
